---
sqs:
  url: http://localhost:4576/queue/iron_queue
  options:
    endpoint: "http://localstack:4576"
    accessKeyId: abc
    secretAccessKey: abc
    region: us-east-1

quotesRest:
  url: localhost:8082
